# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Statistics-Latin
version:      0.04
version_from: lib/Text/Statistics/Latin.pm
installdirs:  site
requires:
    Text::ParseWords:              3.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
